name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run tests
      run: |
        nix develop --command \
          cabal test
    - name: Cache nix store
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ hashFiles('flake.lock') }}
